modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="layersofdescent"
version="1.0.0"
displayName="LayersOfDescent"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="jayso, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.layersofdescent]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.layersofdescent]]
    modId="kleidersplayerrenderer"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.layersofdescent]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.layersofdescent]]
    modId="playeranimator"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration